name: Build and Test Java Spring Boot Application

on:
  push:
    branches: [ "backend-*","bakend*" ]
  pull_request:
    branches: [ 'backend-*',"bakend*"  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean verify

    - name: Run Tests
      run: mvn test